name: TestExternal

on:
  workflow_dispatch:
  push:
  pull_request:
    
jobs:
  test-output:
    steps:
    - name: output
      run: |
        echo ${{ github.repository_owner }}
        echo ${{ github.repository }}

  test-external:
    uses: sysones/rcore-tutorial-v3-with-hal-component/.github/workflows/test-run.yml@ch7
    with:
      # The directory to Top test, which need to be empty or not exist in this repository
      TopTestDirectory: RcoreTest
      CallerPackage: polyhal
      CallerRepository: ${{ github.repository }}
      CallerCommit: ${{ github.sha }}
  