name: TestExternal

on:
  workflow_dispatch:
  push:
  pull_request:
    
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: output
      run: |
        echo ${{ github.repository_owner }}
        echo ${{ github.repository }}

  test-external:
    if: github.repository_owner == 'sysones'
    strategy:
      fail-fast: false
      matrix:
        branch: [ch7]
    uses: sysones/rcore-tutorial-v3-with-hal-component/.github/workflows/test-run.yml@${{ matrix.branch }}
    with:
      # The directory to Top test, which need to be empty or not exist in this repository
      TopTestDirectory: RcoreTest
      CallerPackage: polyhal
      CallerRepository: ${{ github.repository }}
      CallerCommit: ${{ github.sha }}
